### ISSUE TITLE
get method of the endpoint /user does not works 

### ISSUE THREAD

**Issue by m0dern6** [lgic-project/Service_pro#7]
![image](https://github.com/lgic-project/Service_pro/assets/108034183/65f208a9-60d1-4ab8-981b-966060dd995a)
![image](https://github.com/lgic-project/Service_pro/assets/108034183/0cdf4d15-7355-4a50-8559-e51535a1cd16)
have tried both, with token or without token, but it does not works but category and service endpoints are working

**Comment by 0Ankit0** [comment]
solved the issue.
